config/routes.rb
TCC::Application.routes.draw do

  resources :events

  resources :investor_groups

  resources :interests

  resources :statistics

  resources :products

  resources :showcases

  resources :startups

  resources :messages

  resources :investors#, :only => [:show, :create, :edit, :destroy]

  resources :upgrades

  resources :rankings

  resources :badges

  resources :credit_cards

  resources :payments

  resources :feeds

  resources :reports

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  resources :users
  resources :posts, only: [:index, :create, :destroy]
  resources :friendship, only: [:create, :destroy]
  root :to => 'home#show'


  # Home
  match 'home', to: 'home#show', via: :all
  match 'index', to: 'home#index', as: 'home_index'

  # Users
  match '/users/:id/settings', to: 'users#settings', as: 'settings_user'

  # Messages
   match 'select_user', to: 'messages#select'
  match 'show_user', to: 'messages#showuser'

	# Investors
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  attr_accessible :name, :point
end

app/controllers/rankings_controller.rb
class RankingsController < InheritedResources::Base
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_for(@ranking) do |f| %>
  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% @ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rankings/edit.html.erb
<h1>Editing ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Point</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rankings.each do |ranking| %>
  <tr>
    <td><%= ranking.name %></td>
    <td><%= ranking.point %></td>
    <td><%= link_to 'Show', ranking %></td>
    <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
    <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ranking.name %>
</p>

<p>
  <b>Point:</b>
  <%= @ranking.point %>
</p>


<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>