config/routes.rb
TCC::Application.routes.draw do

  resources :events

  resources :investor_groups

  resources :interests

  resources :statistics

  resources :products

  resources :showcases

  resources :startups

  resources :messages

  resources :investors#, :only => [:show, :create, :edit, :destroy]

  resources :upgrades

  resources :rankings

  resources :badges

  resources :credit_cards

  resources :payments

  resources :feeds

  resources :reports

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  resources :users
  resources :posts, only: [:index, :create, :destroy]
  resources :friendship, only: [:create, :destroy]
  root :to => 'home#show'


  # Home
  match 'home', to: 'home#show', via: :all
  match 'index', to: 'home#index', as: 'home_index'

  # Users
  match '/users/:id/settings', to: 'users#settings', as: 'settings_user'

  # Messages
   match 'select_user', to: 'messages#select'
  match 'show_user', to: 'messages#showuser'

	# Investors
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :description, :image, :name

  belongs_to :user
  
  has_many :user, :class_name => User, :foreign_key => :user_id

  # Paperclip
  has_attached_file :image,
  #:styles => { :thumbnail => "25x25>", :medium => "100x100>" },
  :url => "/assets/images/badges/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/badges/:id/:style/:basename.:extension"

  #validates_attachment_size :photo, :less_than => 5.megabytes
  #validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/badges_controller.rb
class BadgesController < InheritedResources::Base
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges.each do |badge| %>
  <tr>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td><%= badge.image %></td>
    <td><%= link_to 'Show', badge %></td>
    <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
    <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @badge.name %>
</p>

<p>
  <b>Description:</b>
  <%= @badge.description %>
</p>

<p>
  <b>Image:</b>
  <%= @badge.image %>
</p>


<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>