config/routes.rb
TCC::Application.routes.draw do

  resources :events

  resources :investor_groups

  resources :interests

  resources :statistics

  resources :products

  resources :showcases

  resources :startups

  resources :messages

  resources :investors#, :only => [:show, :create, :edit, :destroy]

  resources :upgrades

  resources :rankings

  resources :badges

  resources :credit_cards

  resources :payments

  resources :feeds

  resources :reports

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  resources :users
  resources :posts, only: [:index, :create, :destroy]
  resources :friendship, only: [:create, :destroy]
  root :to => 'home#show'


  # Home
  match 'home', to: 'home#show', via: :all
  match 'index', to: 'home#index', as: 'home_index'

  # Users
  match '/users/:id/settings', to: 'users#settings', as: 'settings_user'

  # Messages
   match 'select_user', to: 'messages#select'
  match 'show_user', to: 'messages#showuser'

	# Investors
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  attr_accessible :date, :flag, :name, :number, :seg_cod, :user_id
  validates_presence_of :date, :flag, :name, :number, :seg_cod, presence => true
  belongs_to :user
  belongs_to :upgrade 
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < InheritedResources::Base

  def destroy
    @card = CreditCard.find(params[:card_id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to :back }
    end
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label "Bandeira do Cartão" %><br />
    <%= f.select :flag,   [['American Express', 'American Express'],['VISA', 'VISA'],['Dinners', 'Dinners'],['MasterCard', 'MasterCard']], { include_blank: true } %>
  </div><br>
  <div class="field">
    <%= f.label "Nome no Cartão" %><br />
    <%= f.text_field :name, :class => "span3"%>
  </div>
  <div class="field">
    <%= f.label "Numero do Cartão" %><br />
    <%= f.text_field :number, :class => "span3"%>
  </div>
  <div class="field">
    <%= f.label "Data de Validade" %><br />
    <%= f.text_field :date %>
  </div>
  
  <div class="field">
    <%= f.label "Codigo de Segurança" %><br />
    <%= f.text_field :seg_cod, :class => "span1"%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<div class="widget-content">
<h1 class="page-title">Seus Cartões de Crédito</h1>

Para que suas transações financeiras sejam realizadas, cadastre seu cartão de credito.<br><br>


<br>
Lista de Cartões Cadastrados:


<table class="table">
  <tr>
    <th>Bandeira</th>
    <th>Número do Cartão</th>
  </tr>

<% CreditCard.where("user_id = ?",current_user.id).each do |credit_card| %>
  <tr>
    <td><%= credit_card.flag %></td>
    <td><%= credit_card.number %></td>
    <td><%= button_to 'Remover Cartão', credit_card, method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar Cartão de Crédito', new_credit_card_path, :class => "btn" %>
</div>

app/views/credit_cards/new.html.erb
<h1 class="page-title">Cadastro de Cartão de Crédito</h1>

<%= render 'form' %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Flag:</b>
  <%= @credit_card.flag %>
</p>

<p>
  <b>Name:</b>
  <%= @credit_card.name %>
</p>

<p>
  <b>Number:</b>
  <%= @credit_card.number %>
</p>

<p>
  <b>Date:</b>
  <%= @credit_card.date %>
</p>

<p>
  <b>Seg cod:</b>
  <%= @credit_card.seg_cod %>
</p>


<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>